version: '3.9'

services:

  app:
    restart: always
    expose:
      - 8000
    links:
      - db:db
    env_file: ./docker/.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /app/docker/docker_prod.sh
    depends_on:
      - db
    volumes:
      - static:/app/carsapi/static
      - project:/app

  nginx:
    restart: always
    build: ./docker/nginx
    ports:
      - 80:80
    depends_on:
      - app
    links:
      - app
    volumes:
      - static:/app/carsapi/static

  db:
    image: postgres
    restart: always
    env_file: ./docker/.env
    ports:
      - 5432:5432

volumes:
  static:
  project:    